apiVersion: v1
kind: Pod
metadata:
  name: config-aop-volume-pod
spec:
  containers:
    - name: test-container
      image: 47.56.30.57/k8s/k8s-study:v2
      command:
        - /bin/sh
        - -c
        - cat /etc/config/special.how
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  restartPolicy: Never