apiVersion: v1
kind: Pod
metadata:
  name: config-aop-2
spec:
  containers:
    - name: config-aop-container
      image: 47.56.30.57/k8s/k8s-study:v2
      command: ["/bin/sh", "-c", "echo ${SPECIAL_LEVEL_KEY} ${SPECIAL_TYPE_KEY}"]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special-config
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.type
  restartPolicy: Never