apiVersion: v1
kind: Pod
metadata:
  name: test-docker-registry-pod
spec:
  containers:
    - name: test-docker-container
      image: 47.56.30.57/k8s/k8s-study:v1
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: docker-registry