apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  docker-server: 47.56.30.57
  docker-email: yundi.xxii@outlook.com
  docker-username: admin
  docker-password: Harbor.xxii6868