apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: Opaque
data:
  docker-server: NDcuNTYuMzAuNTc=
  docker-email: eXVuZGkueHhpaUBvdXRsb29rLmNvbQ==
  docker-username: YWRtaW4=
  docker-password: SGFyYm9yLnh4aWk2ODY4