apiVersion: v1
kind: Pod
metadata:
  name: livenessprobe-tcp
spec:
  containers:
    - name: liveness-tcp-container
      image: 47.56.30.57/k8s/k8s-study:1.0
      livenessProbe:
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 3
        tcpSocket:
          port: 8080