apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
spec:
  replicas: 7
  selector:
    matchLabels:
      - app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      nodeName: k8s-node2
      containers:
        - name: myapp-container
          image: 47.56.30.57/k8s/k8s-study:v2
          ports:
            - containerPort: 8080