apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app: pod-3
spec:
  containers:
    - name: pod-3
      image: 47.56.30.57/k8s/k8s-study:v1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-node1
  tolerations:
    - key: "check"
      operator: "Equal"
      value: "yundi"
      effect: "NoExecute"
      tolerationSeconds: 3600
