apiVersion: v1
kind: Pod
metadata:
  name: node1-pod
  labels:
    app: pod-1
spec:
  containers:
    - name: node1-container
      image: 47.56.30.57/k8s/k8s-study:v1
      imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-node1
  imagePullSecrets:
    - name: myregistrykey