apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-pod
  labels:
    app: pod-3
spec:
  containers:
    - name: pod-affinity-container
      image: 47.56.30.57/k8s/k8s-study:v2
      imagePullPolicy: IfNotPresent
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - node1-pod
          topologyKey: kubernetes.io/hostname
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - pod-2
            topologyKey: kubernetes.io/hostname
  imagePullSecrets:
    - name: myregistrykey