# 就绪检测加存活检测
apiVersion: v1
kind: Pod
metadata:
  name: readiness-liveness-pod
  namespace: default
spec:
  containers:
    - name: readiness-liveness-container
      image: 47.56.30.57/k8s/k8s-study:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - name: tcp
          containerPort: 80
      readinessProbe:
        httpGet:
          port: tcp
          path: /
        initialDelaySeconds: 5
        periodSeconds: 3
        timeoutSeconds: 1
      livenessProbe:
        tcpSocket:
          port: tcp
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 3