# 检测探针，就绪检测
apiVersion: v1
kind: Pod
metadata:
  name: readiness-httpget-pod
  namespace: default
spec:
  containers:
    - name: readiness-httpget-container
      image: 47.56.30.57/k8s/k8s-study:1.0
      imagePullPolicy: IfNotPresent
      readinessProbe:
        httpGet:
          port: 8080
          path: /
        initialDelaySeconds: 1
        periodSeconds: 3