apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod
  labels:
    app: node-affinity-pod
spec:
  containers:
    - name: with-node-affinity
      image: 47.56.30.57/k8s/k8s-study:v1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - k8s-node2
# operator: 键值运算关系
# In: label的值在某个列表中
# NotIn: label的值不再某个列表中
# Gt：label的值大于某个值
# Lt：label的值小于某个值
# Exists：某个label存在
# DoesNotExist：某个label不存在
