apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod
  labels:
    app: node-affinity-pod
spec:
  containers:
    - name: with-node-affinity
      image: 47.56.30.57/k8s/k8s-study:v1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - k8s-node2