apiVersion: v1
kind: Pod
metadata:
  name: affinity
  labels:
    app: node-affinity-prefer-pod
spec:
  containers:
    - name: node-affinity-prefer-container
      image: 47.56.30.57/k8s/k8s-study:v2
      imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-node2

  imagePullSecrets:
    - name: myregistrykey