# secret导出到环境变量
apiVersion: apps/v1
kind: Deployment
meatadata:
  name: deployment-pod
spec:
  replicas: 2
  matchLabels:
    app: deployment-pod
  template:
    meatadata:
      labels:
        app: deployment-pod
    spec:
      containers:
        - name: pod-1
          image: 47.56.30.57/k8s/k8s-study:v1
          ports:
            - containerPort: 8080
          env:
            - name: TEST_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: TEST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password