apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - image: k8s.gcr.io/test-webserver
      name: test-container
      volumeMounts:
        - mountPath: /test-pod
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        # 主机上的文件夹路径
        path: /data
        type: Directory